env: LC_ALL=C
before_script:
  - wget -q http://gentoo.osuosl.org/releases/x86/autobuilds/latest-stage3-i686.txt
  - wget -q http://gentoo.osuosl.org/releases/x86/autobuilds/$(tail -1 latest-stage3-i686.txt) -O stage3.tar.bz2
  - mkdir gentoo
  - sudo tar xpf stage3.tar.bz2 -C gentoo
  - sudo mount -o bind /dev gentoo/dev
  - sudo mount -t proc none gentoo/proc
  - sudo mount -t sysfs none gentoo/sys
  - sudo cp -L /etc/resolv.conf gentoo/etc/resolv.conf
  - sudo chroot gentoo emerge-webrsync -q
  - sudo chroot gentoo emerge --quiet --sync
script:
  - sudo chroot gentoo ls -la
